#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Final R3 summary."""

import json
import requests

SUPABASE_URL = "https://wmugemamnqxjfpxrlwes.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtdWdlbWFtbnF4amZweHJsd2VzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NjA5ODA0NywiZXhwIjoyMDkxNjc0MDQ3fQ.jNPXyxt6IqhZ-GCJBsmDqQOz9PKHuAXKf30aJfHYfoo"

url = f"{SUPABASE_URL}/rest/v1/occurrences"
headers = {
    "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}",
    "Content-Type": "application/json",
    "apikey": SUPABASE_SERVICE_ROLE_KEY,
}

# Get all occurrences with range header to get count
response = requests.get(f"{url}?limit=10000", headers=headers)
all_data = response.json()

# Count by tipo
tipo_count = {}
severity_count = {}
for occ in all_data:
    tipo = occ.get('tipo', 'UNKNOWN')
    severity = occ.get('severity', 'UNKNOWN')
    tipo_count[tipo] = tipo_count.get(tipo, 0) + 1
    if tipo not in severity_count:
        severity_count[tipo] = {}
    severity_count[tipo][severity] = severity_count[tipo].get(severity, 0) + 1

print("\n" + "="*80)
print("R3 IMPLEMENTATION - FINAL SUMMARY")
print("="*80 + "\n")

print("Occurrences Generated by Rule Type:")
print("-" * 80)
for tipo in sorted(tipo_count.keys()):
    count = tipo_count[tipo]
    sev_str = ", ".join([f"{s}:{c}" for s, c in sorted(severity_count[tipo].items())])
    print(f"  {tipo:30} {count:6} occurrences  ({sev_str})")

total = sum(tipo_count.values())
print("-" * 80)
print(f"  {'TOTAL':30} {total:6} occurrences\n")

# Check R3 specific
r3_count = tipo_count.get('EVOLUCAO_ATRASADA', 0)
print(f"R3 Detection Result: {r3_count} sessions without evolution/treatment")
print("\n" + "="*80 + "\n")
