  analise/warnings-supabase[m
  aperfeicoamento/conferencia-assim[m
  auditoria-assim[m
  calc-remuneracao[m
  chore/limpeza-relacoes-mortas[m
  clickup/msg-glosa[m
  conciliacao-evolucao[m
  conciliacao-evolucao-frontend[m
  correcao/previsao-de-remuneracao[m
  correcao/quebra-processo-nao-e-glosa[m
  cronograma[m
  design[m
  docs/advisors-fase3-aplicada[m
  fase1-congelar-historico-grade[m
  fase2-execucao-tratativa-grade[m
  feat/analise-tratativas[m
  feat/auditoria-assim-detalhamento-atendimento[m
  feat/autorizacao-pacientes[m
  feat/central-alertas-pendencias-assim[m
  feat/central-atendimento[m
  feat/central-pacientes-redesign[m
  feat/cronograma-grade-profissionais-api[m
  feat/depois-do-vinculo-reconciliacao[m
  feat/insumos-axium[m
  feat/lista-pendencias-badges[m
  feat/monitoramento-assim-e-autorizacoes-avulsas[m
  feat/reconciliacao-autorizacoes-assim[m
  feat/robo-token-por-maquina[m
  feat/tita-api-agendamento[m
  feat/tv-chamada-paciente[m
  feat/visao-gerencial-auditoria-assim[m
  feature/correcao-inconsistencias-pulsar-jul2026[m
  fix/advisors-rls-views-e-blacklist[m
  fix/central-pacientes-estabilizacao[m
  fix/central-terapeutas-timeout[m
  fix/enrich-tita-csv-fields[m
  fix/guia-autorizacao-antecipada[m
  fix/icone-quadrado[m
  fix/replay-migrations-e-drift-prod[m
  fix/rls-disponibilidade-terapeuta[m
  fix/tuss-fallback-exibicao-tita[m
  fix/worker-online-e-cancelamento[m
  indicadores/profissional[m
  login[m
* [32mmain[m
  modulo/financeiro[m
  ocupacao-paciente[m
  perf/disk-io-budget[m
  redesign/relacionamento-prestador-total[m
  reposicao-faltas[m
  security/phase0[m
  solicitacao[m
  substituicao-terapeuta[m
