-- Seed de alocações reais, gerado a partir de TODO o histórico sincronizado
-- de csv_grades_profissionais (17.156 agendamentos "Agendado" analisados).
--
-- Para cada sala física × dia da semana × turno, identificado o(s)
-- profissional(is) que aparece(m) com mais frequência nesse bloco ao longo
-- de todo o histórico sincronizado (não só a semana de referência), até o
-- limite da capacidade da sala (único=1, duplo=2, múltiplo=3). A terapia
-- escolhida é a mais frequente desse profissional nesse mesmo bloco.
--
-- Texto (profissional/terapia) reparado do mojibake de dupla codificação
-- UTF-8 que a sincronização da grade grava (mesmo tratamento de
-- frontend/lib/cronograma/gradeService.ts:fixMojibake).
--
-- IMPORTANTE: isso é planejamento (tabela cronograma_salas_alocacoes) — não
-- toca em nenhum dado real de agendamento. Se a "pessoa mais frequente" não
-- bater com a realidade atual da operação (substituições, mudanças recentes
-- de escala etc.), é só editar/mover pela tela normalmente.
--
-- 519 alocações geradas.

-- Replay fix: este seed gravava sala_id com os UUIDs literais de produção,
-- mas cronograma_salas.id é gen_random_uuid() — num replay do zero (db reset
-- / db pull) as salas nascem com outros UUIDs e os 519 INSERTs quebravam com
-- FK violation (23503). Agora resolve a sala pela chave natural
-- (unidade_nome + numero_sala), que é única nas 87 salas. Mesmas 519
-- alocações, mesmas 55 salas — só a forma de referenciar mudou.

insert into public.cronograma_salas_alocacoes (sala_id, dow, turno, profissional_nome, terapia_nome)
select s.id, v.dow, v.turno, v.profissional_nome, v.terapia_nome
from (values
  ('Fazendinha', '1', 2, 'Manhã', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '1', 2, 'Tarde', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '1', 4, 'Manhã', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '1', 4, 'Manhã', 'Yasmin Souza Meirelles Oliveira', 'Psicopedagogia'),
  ('Fazendinha', '1', 4, 'Tarde', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '1', 4, 'Tarde', 'Yasmin Souza Meirelles Oliveira', 'Psicopedagogia'),
  ('Fazendinha', '10', 3, 'Tarde', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '10', 4, 'Manhã', 'Ingrid Cassia de Andrade', 'Equoterapia'),
  ('Fazendinha', '10', 4, 'Tarde', 'Ingrid Cassia de Andrade', 'Equoterapia'),
  ('Fazendinha', '11', 1, 'Manhã', 'Isabela Suzana De Andrade Barbosa', 'Psicologia ABA'),
  ('Fazendinha', '11', 1, 'Manhã', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '11', 1, 'Manhã', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '11', 1, 'Tarde', 'Isabela Suzana De Andrade Barbosa', 'Psicologia ABA'),
  ('Fazendinha', '11', 1, 'Tarde', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '11', 1, 'Tarde', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '11', 2, 'Manhã', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '11', 2, 'Manhã', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '11', 2, 'Tarde', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '11', 2, 'Tarde', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '11', 3, 'Manhã', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '11', 3, 'Tarde', 'Gracielle Rayane Faria Miranda', 'Psicologia ABA'),
  ('Fazendinha', '11', 4, 'Manhã', 'Isabela Suzana De Andrade Barbosa', 'Psicologia ABA'),
  ('Fazendinha', '11', 4, 'Manhã', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '11', 4, 'Manhã', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '11', 4, 'Tarde', 'Isabela Suzana De Andrade Barbosa', 'Psicologia ABA'),
  ('Fazendinha', '11', 4, 'Tarde', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '11', 4, 'Tarde', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '11', 5, 'Manhã', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '11', 5, 'Tarde', 'Gracielle Rayane Faria Miranda', 'Psicologia ABA'),
  ('Fazendinha', '11', 5, 'Tarde', 'Marcelle Cabral Volpasso', 'Operações Clínicas'),
  ('Fazendinha', '12', 1, 'Manhã', 'Bruna Ferreira Araujo', 'Psicologia ABA'),
  ('Fazendinha', '12', 1, 'Tarde', 'Bruna Ferreira Araujo', 'Psicologia ABA'),
  ('Fazendinha', '12', 1, 'Tarde', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '12', 2, 'Manhã', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '12', 2, 'Manhã', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '12', 2, 'Tarde', 'Bruna Ferreira Araujo', 'Psicologia ABA'),
  ('Fazendinha', '12', 2, 'Tarde', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '12', 3, 'Manhã', 'Bruna Ferreira Araujo', 'Psicologia ABA'),
  ('Fazendinha', '12', 3, 'Tarde', 'Bruna Ferreira Araujo', 'Psicologia ABA'),
  ('Fazendinha', '12', 4, 'Manhã', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '12', 4, 'Tarde', 'João Gabriel Barbosa De Souza', 'Psicologia ABA'),
  ('Fazendinha', '12', 4, 'Tarde', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '12', 5, 'Tarde', 'Bruna Ferreira Araujo', 'Psicologia ABA'),
  ('Fazendinha', '12', 5, 'Tarde', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Fazendinha', '2', 1, 'Manhã', 'Rachel Silva De Castro De Brito', 'Musicoterapia'),
  ('Fazendinha', '2', 1, 'Tarde', 'Rachel Silva De Castro De Brito', 'Musicoterapia'),
  ('Fazendinha', '2', 2, 'Manhã', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '2', 4, 'Manhã', 'Rachel Silva De Castro De Brito', 'Musicoterapia'),
  ('Fazendinha', '2', 4, 'Tarde', 'Rachel Silva De Castro De Brito', 'Musicoterapia'),
  ('Fazendinha', '2', 5, 'Manhã', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Fazendinha', '2', 5, 'Tarde', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Fazendinha', '2', 5, 'Tarde', 'Yasmin Souza Meirelles Oliveira', 'Psicopedagogia'),
  ('Fazendinha', '3', 2, 'Tarde', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '3', 2, 'Tarde', 'Willian da Silva Santos', 'Psicologia ABA'),
  ('Fazendinha', '3', 3, 'Tarde', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Fazendinha', '3', 4, 'Manhã', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '3', 4, 'Manhã', 'Yasmin Souza Meirelles Oliveira', 'Psicopedagogia'),
  ('Fazendinha', '3', 4, 'Tarde', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia ABA'),
  ('Fazendinha', '3', 4, 'Tarde', 'Yasmin Souza Meirelles Oliveira', 'Psicopedagogia'),
  ('Fazendinha', '3', 5, 'Tarde', 'Yasmin Souza Meirelles Oliveira', 'Psicopedagogia'),
  ('Fazendinha', '4', 1, 'Manhã', 'Rachel Silva De Castro De Brito', 'Musicoterapia'),
  ('Fazendinha', '4', 1, 'Tarde', 'Rachel Silva De Castro De Brito', 'Musicoterapia'),
  ('Fazendinha', '4', 3, 'Tarde', 'Nathalia de Lyra Silva Rezende Freitas Inacio', 'Psicologia ABA'),
  ('Fazendinha', '4', 4, 'Manhã', 'Rachel Silva De Castro De Brito', 'Psicologia ABA'),
  ('Fazendinha', '4', 4, 'Tarde', 'Rachel Silva De Castro De Brito', 'Musicoterapia'),
  ('Fazendinha', '4', 5, 'Manhã', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Fazendinha', '4', 5, 'Tarde', 'Maria Eduarda Marrocos', 'Fonoaudiologia'),
  ('Fazendinha', '5', 3, 'Tarde', 'Priscila Gottgtroy Gois', 'Terapia Alimentar'),
  ('Fazendinha', '5', 4, 'Manhã', 'Juliana Fraga Sampaio', 'Terapia Alimentar'),
  ('Fazendinha', '5', 4, 'Tarde', 'Juliana Fraga Sampaio', 'Terapia Alimentar'),
  ('Fazendinha', '7', 1, 'Manhã', 'Ana Tereza Rezende Nascimento', 'Fisioterapia'),
  ('Fazendinha', '7', 1, 'Tarde', 'Ana Tereza Rezende Nascimento', 'Fisioterapia'),
  ('Fazendinha', '7', 2, 'Manhã', 'Joseane Bezerra Dos Santos De Castro', 'Psicologia'),
  ('Fazendinha', '7', 2, 'Manhã', 'Mirlley de Jesus Medeiros', 'Terapia Ocupacional'),
  ('Fazendinha', '7', 2, 'Tarde', 'Mirlley de Jesus Medeiros', 'Terapia Ocupacional'),
  ('Fazendinha', '7', 3, 'Manhã', 'Juliana Soares Rodrigues', 'Psicomotricidade'),
  ('Fazendinha', '7', 3, 'Manhã', 'Larissa Neivane Caslow Assunção', 'Fisioterapia'),
  ('Fazendinha', '7', 3, 'Manhã', 'Mirlley de Jesus Medeiros', 'Terapia Ocupacional'),
  ('Fazendinha', '7', 3, 'Tarde', 'Larissa Neivane Caslow Assunção', 'Fisioterapia'),
  ('Fazendinha', '7', 3, 'Tarde', 'Mirlley de Jesus Medeiros', 'Terapia Ocupacional'),
  ('Fazendinha', '7', 3, 'Tarde', 'Thaísa Raquel Souza Da Gama Sarmento Dos Santos', 'Psicomotricidade'),
  ('Fazendinha', '7', 4, 'Manhã', 'Elisangela Motta Do Valle', 'Terapia Ocupacional'),
  ('Fazendinha', '7', 4, 'Manhã', 'Juliana Soares Rodrigues', 'Psicomotricidade'),
  ('Fazendinha', '7', 4, 'Tarde', 'Elisangela Motta Do Valle', 'Terapia Ocupacional'),
  ('Fazendinha', '7', 4, 'Tarde', 'Juliana Soares Rodrigues', 'Psicomotricidade'),
  ('Fazendinha', '8', 1, 'Manhã', 'Kesia Passos Antunes Fabiano', 'Fonoaudiologia'),
  ('Fazendinha', '8', 1, 'Tarde', 'Kesia Passos Antunes Fabiano', 'Fonoaudiologia'),
  ('Fazendinha', '8', 2, 'Manhã', 'Cláudia Vieira Imenes', 'Fonoaudiologia'),
  ('Fazendinha', '8', 2, 'Tarde', 'Cláudia Vieira Imenes', 'Fonoaudiologia'),
  ('Fazendinha', '8', 3, 'Manhã', 'Luana Da Conceição Pedro', 'Fonoaudiologia'),
  ('Fazendinha', '8', 3, 'Tarde', 'Luana Da Conceição Pedro', 'Fonoaudiologia'),
  ('Fazendinha', '8', 4, 'Manhã', 'Carina da Silva Moreira', 'Fonoaudiologia'),
  ('Fazendinha', '8', 4, 'Tarde', 'Carina da Silva Moreira', 'Fonoaudiologia'),
  ('Fazendinha', '8', 5, 'Manhã', 'Juliana Arcanjo Carvalho Moreira', 'Fonoaudiologia'),
  ('Fazendinha', '8', 5, 'Tarde', 'Juliana Arcanjo Carvalho Moreira', 'Fonoaudiologia'),
  ('Fazendinha', '9', 1, 'Manhã', 'Ana Tereza Rezende Nascimento', 'Fisioterapia Aquática'),
  ('Fazendinha', '9', 1, 'Tarde', 'Ana Tereza Rezende Nascimento', 'Fisioterapia Aquática'),
  ('Fazendinha', '9', 2, 'Tarde', 'Ana Tereza Rezende Nascimento', 'Fisioterapia Aquática'),
  ('Padre Miguel', '1', 1, 'Manhã', 'Crislaine Neves da Silva', 'Avaliação Neuropsicológica'),
  ('Padre Miguel', '1', 1, 'Tarde', 'Crislaine Neves da Silva', 'Avaliação Neuropsicológica'),
  ('Padre Miguel', '1', 2, 'Manhã', 'Crislaine Neves da Silva', 'Avaliação Neuropsicológica'),
  ('Padre Miguel', '1', 2, 'Tarde', 'Crislaine Neves da Silva', 'Avaliação Neuropsicológica'),
  ('Padre Miguel', '1', 3, 'Tarde', 'João Luiz Ramos de Souza', 'Psiquiatra/Neurologista'),
  ('Padre Miguel', '10', 3, 'Manhã', 'Sabrina Santos Theobaldo', 'Psicopedagogia'),
  ('Padre Miguel', '10', 3, 'Tarde', 'Sabrina Santos Theobaldo', 'Psicopedagogia'),
  ('Padre Miguel', '11', 2, 'Manhã', 'Nathalia Medeiros D'' Aniello', 'Triagem'),
  ('Padre Miguel', '12', 2, 'Manhã', 'Stephanie Amado Diogo Nogueira', 'Fonoaudiologia'),
  ('Padre Miguel', '12', 2, 'Tarde', 'Stephanie Amado Diogo Nogueira', 'Fonoaudiologia'),
  ('Padre Miguel', '12', 3, 'Manhã', 'Stephanie Amado Diogo Nogueira', 'Fonoaudiologia'),
  ('Padre Miguel', '12', 3, 'Tarde', 'Stephanie Amado Diogo Nogueira', 'Fonoaudiologia'),
  ('Padre Miguel', '13', 2, 'Tarde', 'Amanda Báfica De Castro E Silva', 'Psicologia'),
  ('Padre Miguel', '13', 3, 'Manhã', 'Amanda Báfica De Castro E Silva', 'Psicologia'),
  ('Padre Miguel', '13', 3, 'Tarde', 'Amanda Báfica De Castro E Silva', 'Psicologia'),
  ('Padre Miguel', '13', 5, 'Manhã', 'Marcy Helem Corrêa Fernandes de Freitas Piovesan', 'Fonoaudiologia'),
  ('Padre Miguel', '13', 5, 'Tarde', 'Marcy Helem Corrêa Fernandes de Freitas Piovesan', 'Fonoaudiologia'),
  ('Padre Miguel', '14', 2, 'Manhã', 'Elisangela Motta Do Valle', 'Terapia Ocupacional'),
  ('Padre Miguel', '14', 2, 'Tarde', 'Elisangela Motta Do Valle', 'Terapia Ocupacional'),
  ('Padre Miguel', '15', 3, 'Manhã', 'Thaísa Raquel Souza Da Gama Sarmento Dos Santos', 'Psicomotricidade'),
  ('Padre Miguel', '21', 2, 'Tarde', 'Thayná Nascimento De Souza', 'Terapia Ocupacional'),
  ('Padre Miguel', '26', 1, 'Manhã', 'Nathalia Medeiros D'' Aniello', 'Operações Clínicas'),
  ('Padre Miguel', '26', 1, 'Tarde', 'Nathalia Medeiros D'' Aniello', 'Operações Clínicas'),
  ('Padre Miguel', '26', 2, 'Manhã', 'Lorena Corrêa Guimarães', 'Psicologia ABA'),
  ('Padre Miguel', '26', 2, 'Tarde', 'Lorena Corrêa Guimarães', 'Psicologia ABA'),
  ('Padre Miguel', '26', 5, 'Manhã', 'Nathalia Medeiros D'' Aniello', 'Operações Clínicas'),
  ('Padre Miguel', '26', 5, 'Tarde', 'Nathalia Medeiros D'' Aniello', 'Operações Clínicas'),
  ('Padre Miguel', '8', 2, 'Manhã', 'Camila Ferreira Rios Gomes', 'Psicologia ABA'),
  ('Padre Miguel', '9', 3, 'Manhã', 'Rosenilza Abreu Da Silva Leiras', 'Musicoterapia'),
  ('Realengo', '10', 1, 'Manhã', 'Ana Beatriz Virginio Da Silva', 'Psicopedagogia'),
  ('Realengo', '10', 1, 'Tarde', 'Ana Beatriz Virginio Da Silva', 'Psicopedagogia'),
  ('Realengo', '10', 2, 'Manhã', 'Ana Carolyna Barros Leal', 'Psicopedagogia'),
  ('Realengo', '10', 2, 'Tarde', 'Ana Carolyna Barros Leal', 'Psicopedagogia'),
  ('Realengo', '10', 3, 'Tarde', 'Ana Beatriz Virginio Da Silva', 'Psicopedagogia'),
  ('Realengo', '10', 4, 'Manhã', 'Ana Beatriz Virginio Da Silva', 'Psicopedagogia'),
  ('Realengo', '10', 4, 'Tarde', 'Ana Beatriz Virginio Da Silva', 'Psicopedagogia'),
  ('Realengo', '10', 5, 'Manhã', 'Ana Beatriz Virginio Da Silva', 'Psicopedagogia'),
  ('Realengo', '10', 5, 'Tarde', 'Ana Beatriz Virginio Da Silva', 'Psicopedagogia'),
  ('Realengo', '11', 1, 'Manhã', 'Germana Santos da Silva', 'Fonoaudiologia'),
  ('Realengo', '11', 1, 'Tarde', 'Germana Santos da Silva', 'Fonoaudiologia'),
  ('Realengo', '11', 2, 'Manhã', 'Germana Santos da Silva', 'Fonoaudiologia'),
  ('Realengo', '11', 2, 'Tarde', 'Germana Santos da Silva', 'Fonoaudiologia'),
  ('Realengo', '11', 3, 'Manhã', 'Patricia da Silva Souza Santos', 'Fonoaudiologia'),
  ('Realengo', '11', 3, 'Tarde', 'Patricia da Silva Souza Santos', 'Fonoaudiologia'),
  ('Realengo', '11', 4, 'Manhã', 'Germana Santos da Silva', 'Fonoaudiologia'),
  ('Realengo', '11', 4, 'Tarde', 'Germana Santos da Silva', 'Fonoaudiologia'),
  ('Realengo', '11', 5, 'Manhã', 'Germana Santos da Silva', 'Fonoaudiologia'),
  ('Realengo', '11', 5, 'Tarde', 'Germana Santos da Silva', 'Fonoaudiologia'),
  ('Realengo', '12', 3, 'Manhã', 'Ana Tereza Rezende Nascimento', 'Fisioterapia Aquática'),
  ('Realengo', '12', 3, 'Tarde', 'Ana Tereza Rezende Nascimento', 'Fisioterapia Aquática'),
  ('Realengo', '12', 5, 'Tarde', 'Ana Tereza Rezende Nascimento', 'Fisioterapia Aquática'),
  ('Realengo', '13', 1, 'Manhã', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '13', 1, 'Tarde', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '13', 2, 'Manhã', 'Débora Anastacia Pires Porto Jensen', 'Psicomotricidade'),
  ('Realengo', '13', 2, 'Manhã', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '13', 2, 'Tarde', 'Débora Anastacia Pires Porto Jensen', 'Psicomotricidade'),
  ('Realengo', '13', 2, 'Tarde', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '13', 3, 'Manhã', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '13', 3, 'Tarde', 'Camila Santos De Souza Monteiro', 'Psicomotricidade'),
  ('Realengo', '13', 3, 'Tarde', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '13', 4, 'Manhã', 'Camila Santos De Souza Monteiro', 'Psicomotricidade'),
  ('Realengo', '13', 4, 'Manhã', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '13', 4, 'Tarde', 'Camila Santos De Souza Monteiro', 'Psicomotricidade'),
  ('Realengo', '13', 4, 'Tarde', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '13', 5, 'Manhã', 'Débora Anastacia Pires Porto Jensen', 'Psicomotricidade'),
  ('Realengo', '13', 5, 'Manhã', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '13', 5, 'Tarde', 'Débora Anastacia Pires Porto Jensen', 'Psicomotricidade'),
  ('Realengo', '13', 5, 'Tarde', 'Rafael Pontes Pinheiro De Souza', 'Psicomotricidade'),
  ('Realengo', '14', 1, 'Manhã', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '14', 1, 'Tarde', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '14', 2, 'Manhã', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '14', 2, 'Tarde', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '14', 4, 'Tarde', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '14', 5, 'Manhã', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '14', 5, 'Tarde', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '15', 1, 'Manhã', 'Ester Praxedes de Souza', 'Estágio'),
  ('Realengo', '15', 1, 'Manhã', 'Marcelle Andressa Da silva Dorcelino', 'Fonoaudiologia'),
  ('Realengo', '15', 1, 'Tarde', 'Ester Praxedes de Souza', 'Estágio'),
  ('Realengo', '15', 1, 'Tarde', 'Marcelle Andressa Da silva Dorcelino', 'Fonoaudiologia'),
  ('Realengo', '15', 2, 'Manhã', 'Ester Praxedes de Souza', 'Estágio'),
  ('Realengo', '15', 2, 'Manhã', 'Isabella Alves De Oliveira Marciano', 'Fonoaudiologia'),
  ('Realengo', '15', 2, 'Manhã', 'Joice Indiara De Oliveira Medeiros', 'Estágio'),
  ('Realengo', '15', 2, 'Tarde', 'Ester Praxedes de Souza', 'Estágio'),
  ('Realengo', '15', 2, 'Tarde', 'Isabella Alves De Oliveira Marciano', 'Fonoaudiologia'),
  ('Realengo', '15', 2, 'Tarde', 'Joice Indiara De Oliveira Medeiros', 'Estágio'),
  ('Realengo', '15', 3, 'Tarde', 'Cláudia Vieira Imenes', 'Fonoaudiologia'),
  ('Realengo', '15', 4, 'Manhã', 'Isabella Alves De Oliveira Marciano', 'Fonoaudiologia'),
  ('Realengo', '15', 4, 'Manhã', 'Joice Indiara De Oliveira Medeiros', 'Estágio'),
  ('Realengo', '15', 4, 'Tarde', 'Isabella Alves De Oliveira Marciano', 'Fonoaudiologia'),
  ('Realengo', '15', 4, 'Tarde', 'Joice Indiara De Oliveira Medeiros', 'Estágio'),
  ('Realengo', '15', 5, 'Manhã', 'Ester Praxedes de Souza', 'Estágio'),
  ('Realengo', '15', 5, 'Manhã', 'Marcelle Andressa Da silva Dorcelino', 'Fonoaudiologia'),
  ('Realengo', '15', 5, 'Tarde', 'Ester Praxedes de Souza', 'Estágio'),
  ('Realengo', '15', 5, 'Tarde', 'Marcelle Andressa Da silva Dorcelino', 'Fonoaudiologia'),
  ('Realengo', '16', 1, 'Manhã', 'Elaine Ferreira Nunes', 'Fonoaudiologia'),
  ('Realengo', '16', 1, 'Tarde', 'Elaine Ferreira Nunes', 'Fonoaudiologia'),
  ('Realengo', '16', 2, 'Manhã', 'Thais Liberato Silva', 'Fonoaudiologia'),
  ('Realengo', '16', 3, 'Manhã', 'Thais Liberato Silva', 'Fonoaudiologia'),
  ('Realengo', '16', 3, 'Tarde', 'Thais Liberato Silva', 'Fonoaudiologia'),
  ('Realengo', '16', 4, 'Manhã', 'Thais Liberato Silva', 'Fonoaudiologia'),
  ('Realengo', '16', 4, 'Tarde', 'Thais Liberato Silva', 'Fonoaudiologia'),
  ('Realengo', '16', 5, 'Manhã', 'Kesia Passos Antunes Fabiano', 'Fonoaudiologia'),
  ('Realengo', '16', 5, 'Tarde', 'Kesia Passos Antunes Fabiano', 'Fonoaudiologia'),
  ('Realengo', '18', 1, 'Manhã', 'Evelyn Andressa Alves Do Nascimento De Souza', 'Psicologia ABA'),
  ('Realengo', '18', 1, 'Manhã', 'Rayanne Pimentel De Mendonça', 'Psicologia ABA'),
  ('Realengo', '18', 1, 'Manhã', 'Tailisse Cristina Silva Giusti', 'Psicologia ABA'),
  ('Realengo', '18', 1, 'Tarde', 'Amanda Ribeiro Campos', 'Psicologia ABA'),
  ('Realengo', '18', 1, 'Tarde', 'Evelyn Andressa Alves Do Nascimento De Souza', 'Psicologia ABA'),
  ('Realengo', '18', 1, 'Tarde', 'Rayanne Pimentel De Mendonça', 'Psicologia ABA'),
  ('Realengo', '18', 2, 'Manhã', 'Amanda Ribeiro Campos', 'Psicologia ABA'),
  ('Realengo', '18', 2, 'Manhã', 'Evelyn Andressa Alves Do Nascimento De Souza', 'Psicologia ABA'),
  ('Realengo', '18', 2, 'Manhã', 'Rayanne Pimentel De Mendonça', 'Psicologia ABA'),
  ('Realengo', '18', 2, 'Tarde', 'Aline De Miranda Costa', 'Psicologia ABA'),
  ('Realengo', '18', 2, 'Tarde', 'Amanda Ribeiro Campos', 'Psicologia ABA'),
  ('Realengo', '18', 2, 'Tarde', 'Janine Lara Da Conceição Silva', 'Psicologia ABA'),
  ('Realengo', '18', 3, 'Manhã', 'Amanda Ribeiro Campos', 'Psicologia ABA'),
  ('Realengo', '18', 3, 'Manhã', 'Janine Lara Da Conceição Silva', 'Psicologia ABA'),
  ('Realengo', '18', 3, 'Manhã', 'Tailisse Cristina Silva Giusti', 'Psicologia ABA'),
  ('Realengo', '18', 3, 'Tarde', 'Aline De Miranda Costa', 'Psicologia ABA'),
  ('Realengo', '18', 3, 'Tarde', 'Evelyn Andressa Alves Do Nascimento De Souza', 'Psicologia ABA'),
  ('Realengo', '18', 3, 'Tarde', 'Tailisse Cristina Silva Giusti', 'Psicologia ABA'),
  ('Realengo', '18', 4, 'Manhã', 'Aline De Miranda Costa', 'Psicologia ABA'),
  ('Realengo', '18', 4, 'Manhã', 'Camila Batista Ferreira', 'Psicologia ABA'),
  ('Realengo', '18', 4, 'Manhã', 'Janine Lara Da Conceição Silva', 'Psicologia ABA'),
  ('Realengo', '18', 4, 'Tarde', 'Aline De Miranda Costa', 'Psicologia ABA'),
  ('Realengo', '18', 4, 'Tarde', 'Camila Batista Ferreira', 'Psicologia ABA'),
  ('Realengo', '18', 4, 'Tarde', 'Janine Lara Da Conceição Silva', 'Psicologia ABA'),
  ('Realengo', '18', 5, 'Manhã', 'Amanda Ribeiro Campos', 'Psicologia ABA'),
  ('Realengo', '18', 5, 'Tarde', 'Amanda Ribeiro Campos', 'Psicologia ABA'),
  ('Realengo', '18', 5, 'Tarde', 'Camila Batista Ferreira', 'Psicologia ABA'),
  ('Realengo', '18', 5, 'Tarde', 'Izabelle Soares Da Silva', 'Psicologia ABA'),
  ('Realengo', '19', 1, 'Manhã', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Realengo', '19', 1, 'Tarde', 'Jéssica Santos Gonçalves', 'Psicologia'),
  ('Realengo', '19', 1, 'Tarde', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Realengo', '19', 2, 'Manhã', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Realengo', '19', 2, 'Tarde', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Realengo', '19', 3, 'Manhã', 'Jéssica Santos Gonçalves', 'Psicologia'),
  ('Realengo', '19', 3, 'Manhã', 'Pauline Mazzei Ventura Silveira', 'Psicologia ABA'),
  ('Realengo', '19', 3, 'Tarde', 'Jéssica Santos Gonçalves', 'Psicologia'),
  ('Realengo', '19', 3, 'Tarde', 'Pauline Mazzei Ventura Silveira', 'Psicologia ABA'),
  ('Realengo', '19', 4, 'Tarde', 'Pauline Mazzei Ventura Silveira', 'Psicologia ABA'),
  ('Realengo', '19', 5, 'Manhã', 'Amanda Báfica De Castro E Silva', 'Psicologia ABA'),
  ('Realengo', '19', 5, 'Tarde', 'Amanda Báfica De Castro E Silva', 'Psicologia'),
  ('Realengo', '19', 5, 'Tarde', 'Nathalia de Lyra Silva Rezende Freitas Inacio', 'Psicologia ABA'),
  ('Realengo', '20', 1, 'Manhã', 'Gabrielly De Souza Silveira Dos Reis', 'Fonoaudiologia'),
  ('Realengo', '20', 1, 'Tarde', 'Gabrielly De Souza Silveira Dos Reis', 'Fonoaudiologia'),
  ('Realengo', '20', 3, 'Manhã', 'Gabrielly De Souza Silveira Dos Reis', 'Fonoaudiologia'),
  ('Realengo', '20', 3, 'Tarde', 'Gabrielly De Souza Silveira Dos Reis', 'Fonoaudiologia'),
  ('Realengo', '20', 3, 'Tarde', 'Patricia da Silva Souza Santos', 'Fonoaudiologia'),
  ('Realengo', '20', 4, 'Manhã', 'Marcia Regina Araujo de Paula', 'Fonoaudiologia'),
  ('Realengo', '20', 4, 'Tarde', 'Marcia Regina Araujo de Paula', 'Fonoaudiologia'),
  ('Realengo', '21', 1, 'Manhã', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '21', 1, 'Manhã', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 1, 'Manhã', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '21', 1, 'Tarde', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '21', 1, 'Tarde', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 1, 'Tarde', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '21', 2, 'Manhã', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '21', 2, 'Manhã', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 2, 'Manhã', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '21', 2, 'Tarde', 'Julliana de Oliveira Mota', 'Terapia Ocupacional'),
  ('Realengo', '21', 2, 'Tarde', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 2, 'Tarde', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '21', 3, 'Manhã', 'Jhenifer Matos De Souza Montes', 'Terapia Ocupacional'),
  ('Realengo', '21', 3, 'Manhã', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 3, 'Tarde', 'Jhenifer Matos De Souza Montes', 'Terapia Ocupacional'),
  ('Realengo', '21', 3, 'Tarde', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 3, 'Tarde', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '21', 4, 'Manhã', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '21', 4, 'Manhã', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 4, 'Manhã', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '21', 4, 'Tarde', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '21', 4, 'Tarde', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 4, 'Tarde', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '21', 5, 'Manhã', 'Elisangela Motta Do Valle', 'Terapia Ocupacional'),
  ('Realengo', '21', 5, 'Manhã', 'Maria Alice Sarmento Jarcem', 'Terapia Ocupacional'),
  ('Realengo', '21', 5, 'Manhã', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 5, 'Tarde', 'Maria Alice Sarmento Jarcem', 'Terapia Ocupacional'),
  ('Realengo', '21', 5, 'Tarde', 'Mayara Jorge Da Silva Pereira', 'Aplicador Suporte'),
  ('Realengo', '21', 5, 'Tarde', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '22', 1, 'Manhã', 'Camila Batista Ferreira', 'Coordenador de Caso'),
  ('Realengo', '22', 1, 'Manhã', 'Gracielle Rayane Faria Miranda', 'Psicologia ABA'),
  ('Realengo', '22', 1, 'Manhã', 'Lorena Corrêa Guimarães', 'Psicologia ABA'),
  ('Realengo', '22', 1, 'Tarde', 'Gracielle Rayane Faria Miranda', 'Psicologia ABA'),
  ('Realengo', '22', 1, 'Tarde', 'Lorena Corrêa Guimarães', 'Psicologia ABA'),
  ('Realengo', '22', 1, 'Tarde', 'Thalia Fernandes Pires de Andrade', 'Psicologia ABA'),
  ('Realengo', '22', 2, 'Manhã', 'Izabelle Soares Da Silva', 'Psicologia ABA'),
  ('Realengo', '22', 2, 'Manhã', 'Janine Lara Da Conceição Silva', 'Psicologia ABA'),
  ('Realengo', '22', 2, 'Manhã', 'Thalia Fernandes Pires de Andrade', 'Psicologia ABA'),
  ('Realengo', '22', 2, 'Tarde', 'Izabelle Soares Da Silva', 'Psicologia ABA'),
  ('Realengo', '22', 2, 'Tarde', 'Rayanne Pimentel De Mendonça', 'Psicologia ABA'),
  ('Realengo', '22', 2, 'Tarde', 'Thalia Fernandes Pires de Andrade', 'Psicologia ABA'),
  ('Realengo', '22', 3, 'Manhã', 'Lorena Corrêa Guimarães', 'Psicologia ABA'),
  ('Realengo', '22', 3, 'Manhã', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Realengo', '22', 3, 'Manhã', 'Pedro Igor Castro Teixeira', 'Psicologia ABA'),
  ('Realengo', '22', 3, 'Tarde', 'Lorena Corrêa Guimarães', 'Psicologia ABA'),
  ('Realengo', '22', 3, 'Tarde', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Realengo', '22', 3, 'Tarde', 'Pedro Igor Castro Teixeira', 'Psicologia ABA'),
  ('Realengo', '22', 4, 'Manhã', 'Gracielle Rayane Faria Miranda', 'Psicologia ABA'),
  ('Realengo', '22', 4, 'Manhã', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Realengo', '22', 4, 'Manhã', 'Pedro Igor Castro Teixeira', 'Psicologia ABA'),
  ('Realengo', '22', 4, 'Tarde', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Realengo', '22', 4, 'Tarde', 'Pedro Igor Castro Teixeira', 'Psicologia ABA'),
  ('Realengo', '22', 4, 'Tarde', 'Thalia Fernandes Pires de Andrade', 'Psicologia ABA'),
  ('Realengo', '22', 5, 'Manhã', 'Gracielle Rayane Faria Miranda', 'Psicologia ABA'),
  ('Realengo', '22', 5, 'Manhã', 'Isabela Suzana De Andrade Barbosa', 'Psicologia ABA'),
  ('Realengo', '22', 5, 'Manhã', 'Izabelle Soares Da Silva', 'Coordenador de Caso'),
  ('Realengo', '22', 5, 'Tarde', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '22', 5, 'Tarde', 'Isabela Suzana De Andrade Barbosa', 'Psicologia ABA'),
  ('Realengo', '22', 5, 'Tarde', 'Izabelle Soares Da Silva', 'Psicologia ABA'),
  ('Realengo', '24', 1, 'Manhã', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '24', 1, 'Tarde', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '24', 2, 'Manhã', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '24', 2, 'Manhã', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '24', 2, 'Tarde', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '24', 3, 'Manhã', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '24', 3, 'Manhã', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '24', 3, 'Tarde', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '25', 1, 'Manhã', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '25', 1, 'Manhã', 'Pedro Igor Castro Teixeira', 'Psicologia ABA'),
  ('Realengo', '25', 1, 'Tarde', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '25', 1, 'Tarde', 'Nathalia de Lyra Silva Rezende Freitas Inacio', 'Psicologia ABA'),
  ('Realengo', '25', 2, 'Manhã', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '25', 2, 'Manhã', 'Pedro Igor Castro Teixeira', 'Psicologia ABA'),
  ('Realengo', '25', 2, 'Tarde', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '25', 2, 'Tarde', 'Pedro Igor Castro Teixeira', 'Psicologia ABA'),
  ('Realengo', '25', 3, 'Manhã', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '25', 3, 'Manhã', 'Pauline Mazzei Ventura Silveira', 'Psicologia ABA'),
  ('Realengo', '25', 3, 'Manhã', 'Yasmim Jeniffer Tavares Silva', 'Psicologia ABA'),
  ('Realengo', '25', 3, 'Tarde', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '25', 3, 'Tarde', 'Yasmim Jeniffer Tavares Silva', 'Psicologia ABA'),
  ('Realengo', '25', 4, 'Manhã', 'Yasmim Jeniffer Tavares Silva', 'Psicologia ABA'),
  ('Realengo', '25', 4, 'Tarde', 'Yasmim Jeniffer Tavares Silva', 'Psicologia ABA'),
  ('Realengo', '25', 5, 'Manhã', 'Michele Sousa Freire de Faria', 'Psicologia ABA'),
  ('Realengo', '25', 5, 'Manhã', 'Nathalia de Lyra Silva Rezende Freitas Inacio', 'Psicologia ABA'),
  ('Realengo', '26', 1, 'Manhã', 'Luana Beatriz de Brito Joaquim', 'Psicologia ABA'),
  ('Realengo', '26', 1, 'Tarde', 'Amanda Báfica De Castro E Silva', 'Psicologia ABA'),
  ('Realengo', '26', 1, 'Tarde', 'Keila de Oliveira Garcia', 'Psicologia ABA'),
  ('Realengo', '26', 2, 'Manhã', 'Luana Beatriz de Brito Joaquim', 'Psicologia ABA'),
  ('Realengo', '26', 2, 'Tarde', 'Keila de Oliveira Garcia', 'Psicologia ABA'),
  ('Realengo', '26', 2, 'Tarde', 'Nicolly Christine da Silva Alcantara', 'Psicologia ABA'),
  ('Realengo', '26', 3, 'Tarde', 'Keila de Oliveira Garcia', 'Psicologia ABA'),
  ('Realengo', '26', 3, 'Tarde', 'Nicolly Christine da Silva Alcantara', 'Psicologia ABA'),
  ('Realengo', '26', 4, 'Manhã', 'Luana Beatriz de Brito Joaquim', 'Psicologia ABA'),
  ('Realengo', '26', 4, 'Tarde', 'Keila de Oliveira Garcia', 'Psicologia ABA'),
  ('Realengo', '26', 4, 'Tarde', 'Nicolly Christine da Silva Alcantara', 'Psicologia ABA'),
  ('Realengo', '26', 5, 'Tarde', 'Keila de Oliveira Garcia', 'Psicologia ABA'),
  ('Realengo', '26', 5, 'Tarde', 'Nicolly Christine da Silva Alcantara', 'Psicologia ABA'),
  ('Realengo', '27', 1, 'Manhã', 'Luana Beatriz de Brito Joaquim', 'Psicologia ABA'),
  ('Realengo', '27', 2, 'Manhã', 'Luana Beatriz de Brito Joaquim', 'Psicologia ABA'),
  ('Realengo', '27', 3, 'Manhã', 'Nathalia de Lyra Silva Rezende Freitas Inacio', 'Psicologia ABA'),
  ('Realengo', '27', 4, 'Manhã', 'Luana Beatriz de Brito Joaquim', 'Psicologia ABA'),
  ('Realengo', '27', 5, 'Manhã', 'Lais de Castro Cerqueira Monteiro', 'Psicologia ABA'),
  ('Realengo', '29', 1, 'Tarde', 'Brenda Rayanne Ferreira', 'Psicologia ABA'),
  ('Realengo', '29', 2, 'Tarde', 'Brenda Rayanne Ferreira', 'Psicologia ABA'),
  ('Realengo', '29', 3, 'Tarde', 'Brenda Rayanne Ferreira', 'Psicologia ABA'),
  ('Realengo', '29', 4, 'Manhã', 'Thalia Fernandes Pires de Andrade', 'Psicologia ABA'),
  ('Realengo', '29', 4, 'Tarde', 'Brenda Rayanne Ferreira', 'Psicologia ABA'),
  ('Realengo', '29', 5, 'Tarde', 'Brenda Rayanne Ferreira', 'Psicologia ABA'),
  ('Realengo', '30', 1, 'Manhã', 'Luana Beatriz de Brito Joaquim', 'Psicologia ABA'),
  ('Realengo', '30', 2, 'Manhã', 'Luana Beatriz de Brito Joaquim', 'Psicologia ABA'),
  ('Realengo', '30', 5, 'Manhã', 'Vanessa Kely Souza do Amaral', 'Psicologia ABA'),
  ('Realengo', '30', 5, 'Tarde', 'Camila Batista Ferreira', 'Psicologia ABA'),
  ('Realengo', '31', 1, 'Manhã', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '31', 1, 'Tarde', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '31', 2, 'Manhã', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '31', 2, 'Tarde', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '31', 3, 'Manhã', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '31', 3, 'Tarde', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '31', 4, 'Manhã', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '31', 4, 'Tarde', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '31', 5, 'Tarde', 'Angela Rocha Miranda De Oliveira', 'Psicologia ABA'),
  ('Realengo', '33', 1, 'Tarde', 'Gabriel Rodrigues Miguel', 'Psicologia ABA'),
  ('Realengo', '33', 2, 'Manhã', 'Gabriel Rodrigues Miguel', 'Psicologia ABA'),
  ('Realengo', '33', 2, 'Tarde', 'Gabriel Rodrigues Miguel', 'Psicologia ABA'),
  ('Realengo', '33', 4, 'Manhã', 'Gabriel Rodrigues Miguel', 'Psicologia ABA'),
  ('Realengo', '33', 4, 'Tarde', 'Gabriel Rodrigues Miguel', 'Psicologia ABA'),
  ('Realengo', '35', 1, 'Manhã', 'Jean Gabriel De Lima Magalhães', 'Facilitador Técnico'),
  ('Realengo', '35', 1, 'Manhã', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '35', 1, 'Tarde', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '35', 2, 'Manhã', 'Jean Gabriel De Lima Magalhães', 'Facilitador Técnico'),
  ('Realengo', '35', 2, 'Manhã', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '35', 2, 'Tarde', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '35', 3, 'Manhã', 'Jean Gabriel De Lima Magalhães', 'Facilitador Técnico'),
  ('Realengo', '35', 3, 'Manhã', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '35', 3, 'Tarde', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '35', 4, 'Manhã', 'Jean Gabriel De Lima Magalhães', 'Facilitador Técnico'),
  ('Realengo', '35', 4, 'Manhã', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '35', 4, 'Tarde', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '35', 5, 'Manhã', 'Jean Gabriel De Lima Magalhães', 'Facilitador Técnico'),
  ('Realengo', '35', 5, 'Manhã', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '35', 5, 'Tarde', 'Julia Silva De Sousa', 'Operações Clínicas'),
  ('Realengo', '36', 2, 'Manhã', 'Juliana Soares Rodrigues', 'Especialista Técnico de Área'),
  ('Realengo', '36', 3, 'Manhã', 'Danielle Galvão Nogueira', 'Especialista Técnico de Área'),
  ('Realengo', '36', 3, 'Manhã', 'Mariana Defante', 'Especialista Técnico de Área'),
  ('Realengo', '36', 3, 'Tarde', 'Mariana Defante', 'Terapia Alimentar'),
  ('Realengo', '37', 1, 'Manhã', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '37', 1, 'Tarde', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '37', 2, 'Manhã', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '37', 2, 'Tarde', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '37', 3, 'Manhã', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '37', 3, 'Tarde', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '37', 4, 'Manhã', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '37', 4, 'Tarde', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '37', 5, 'Manhã', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '37', 5, 'Tarde', 'Sandra Cristina Moura Morais', 'Operações Clínicas'),
  ('Realengo', '38', 1, 'Manhã', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '38', 1, 'Tarde', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '38', 2, 'Manhã', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '38', 2, 'Tarde', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '38', 3, 'Manhã', 'Rachel Silva De Castro De Brito', 'Musicoterapia'),
  ('Realengo', '38', 3, 'Tarde', 'Rachel Silva De Castro De Brito', 'Musicoterapia'),
  ('Realengo', '38', 4, 'Manhã', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '38', 4, 'Tarde', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '38', 5, 'Manhã', 'Ianca Aparecida Gonçalves Izidório', 'Musicoterapia'),
  ('Realengo', '38', 5, 'Tarde', 'Ianca Aparecida Gonçalves Izidório', 'Musicoterapia'),
  ('Realengo', '39', 1, 'Manhã', 'Thiago Henrique Brito Do Nascimento', 'Musicoterapia'),
  ('Realengo', '39', 1, 'Tarde', 'Thiago Henrique Brito Do Nascimento', 'Musicoterapia'),
  ('Realengo', '39', 2, 'Manhã', 'Thiago Henrique Brito Do Nascimento', 'Musicoterapia'),
  ('Realengo', '39', 2, 'Tarde', 'Thiago Henrique Brito Do Nascimento', 'Musicoterapia'),
  ('Realengo', '39', 3, 'Manhã', 'Luiz Gustavo Mello de Araújo', 'Musicoterapia'),
  ('Realengo', '39', 3, 'Tarde', 'Luiz Gustavo Mello de Araújo', 'Musicoterapia'),
  ('Realengo', '39', 4, 'Manhã', 'Luiz Gustavo Mello de Araújo', 'Musicoterapia'),
  ('Realengo', '39', 4, 'Tarde', 'Luiz Gustavo Mello de Araújo', 'Musicoterapia'),
  ('Realengo', '39', 5, 'Manhã', 'Luiz Gustavo Mello de Araújo', 'Musicoterapia'),
  ('Realengo', '39', 5, 'Tarde', 'Luiz Gustavo Mello de Araújo', 'Musicoterapia'),
  ('Realengo', '4', 1, 'Manhã', 'Brena Alves Soares de Barros', 'Psicopedagogia'),
  ('Realengo', '4', 1, 'Tarde', 'Brena Alves Soares de Barros', 'Psicopedagogia'),
  ('Realengo', '4', 2, 'Manhã', 'Brena Alves Soares de Barros', 'Psicopedagogia'),
  ('Realengo', '4', 2, 'Tarde', 'Brena Alves Soares de Barros', 'Psicopedagogia'),
  ('Realengo', '4', 3, 'Manhã', 'Luciana Lima Dos Santos', 'Fonoaudiologia'),
  ('Realengo', '4', 3, 'Tarde', 'Luciana Lima Dos Santos', 'Fonoaudiologia'),
  ('Realengo', '4', 4, 'Manhã', 'Brena Alves Soares de Barros', 'Psicopedagogia'),
  ('Realengo', '4', 4, 'Tarde', 'Brena Alves Soares de Barros', 'Psicopedagogia'),
  ('Realengo', '4', 5, 'Manhã', 'Brena Alves Soares de Barros', 'Psicopedagogia'),
  ('Realengo', '4', 5, 'Tarde', 'Brena Alves Soares de Barros', 'Psicopedagogia'),
  ('Realengo', '40', 2, 'Manhã', 'Pedro Igor Castro Teixeira', 'Psicologia ABA'),
  ('Realengo', '40', 2, 'Tarde', 'Paula Quintanilha De Sousa', 'Psicopedagogia'),
  ('Realengo', '40', 3, 'Tarde', 'Rosenilza Abreu Da Silva Leiras', 'Musicoterapia'),
  ('Realengo', '41', 1, 'Manhã', 'Rafaela De Souza Santos', 'Psicomotricidade'),
  ('Realengo', '41', 1, 'Tarde', 'Rafaela De Souza Santos', 'Psicomotricidade'),
  ('Realengo', '41', 2, 'Manhã', 'Rafaela De Souza Santos', 'Psicomotricidade'),
  ('Realengo', '41', 2, 'Tarde', 'Juliana Soares Rodrigues', 'Psicomotricidade'),
  ('Realengo', '41', 2, 'Tarde', 'Rafaela De Souza Santos', 'Psicomotricidade'),
  ('Realengo', '41', 2, 'Tarde', 'Thaísa Raquel Souza Da Gama Sarmento Dos Santos', 'Psicomotricidade'),
  ('Realengo', '41', 3, 'Manhã', 'Patricia Victor da Silva de Lima', 'Psicomotricidade'),
  ('Realengo', '41', 3, 'Tarde', 'Ana Tereza Rezende Nascimento', 'Fisioterapia'),
  ('Realengo', '41', 3, 'Tarde', 'Juliana Soares Rodrigues', 'Psicomotricidade'),
  ('Realengo', '41', 3, 'Tarde', 'Patricia Victor da Silva de Lima', 'Psicomotricidade'),
  ('Realengo', '41', 4, 'Manhã', 'Rafaela De Souza Santos', 'Psicomotricidade'),
  ('Realengo', '41', 4, 'Tarde', 'Rafaela De Souza Santos', 'Psicomotricidade'),
  ('Realengo', '41', 5, 'Tarde', 'Ana Tereza Rezende Nascimento', 'Fisioterapia'),
  ('Realengo', '41', 5, 'Tarde', 'Débora Anastacia Pires Porto Jensen', 'Psicomotricidade'),
  ('Realengo', '41', 5, 'Tarde', 'Thaísa Raquel Souza Da Gama Sarmento Dos Santos', 'Psicomotricidade'),
  ('Realengo', '42', 1, 'Manhã', 'Amanda Martins Rodrigues', 'Arteterapia (Psicologia ABA)'),
  ('Realengo', '42', 1, 'Tarde', 'Amanda Martins Rodrigues', 'Arteterapia (Psicologia ABA)'),
  ('Realengo', '42', 2, 'Manhã', 'Amanda Martins Rodrigues', 'Arteterapia (Psicologia ABA)'),
  ('Realengo', '42', 2, 'Tarde', 'Amanda Martins Rodrigues', 'Psicologia ABA'),
  ('Realengo', '42', 3, 'Manhã', 'Amanda Martins Rodrigues', 'Psicologia ABA'),
  ('Realengo', '42', 3, 'Tarde', 'Amanda Martins Rodrigues', 'Psicologia ABA'),
  ('Realengo', '42', 4, 'Manhã', 'Amanda Martins Rodrigues', 'Psicologia ABA'),
  ('Realengo', '42', 4, 'Tarde', 'Amanda Martins Rodrigues', 'Arteterapia (Psicologia ABA)'),
  ('Realengo', '42', 5, 'Manhã', 'Amanda Martins Rodrigues', 'Psicopedagogia'),
  ('Realengo', '5', 1, 'Manhã', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '5', 1, 'Manhã', 'Jhenifer Matos De Souza Montes', 'Terapia Ocupacional'),
  ('Realengo', '5', 1, 'Tarde', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '5', 1, 'Tarde', 'Jhenifer Matos De Souza Montes', 'Terapia Ocupacional'),
  ('Realengo', '5', 2, 'Manhã', 'Maria Alice Sarmento Jarcem', 'Terapia Ocupacional'),
  ('Realengo', '5', 2, 'Tarde', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '5', 3, 'Manhã', 'Elisangela Motta Do Valle', 'Terapia Ocupacional'),
  ('Realengo', '5', 3, 'Manhã', 'Julliana de Oliveira Mota', 'Terapia Ocupacional'),
  ('Realengo', '5', 3, 'Manhã', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '5', 3, 'Tarde', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '5', 3, 'Tarde', 'Julliana de Oliveira Mota', 'Terapia Ocupacional'),
  ('Realengo', '5', 3, 'Tarde', 'Vivian Menendes dos Santos', 'Terapia Ocupacional'),
  ('Realengo', '5', 4, 'Manhã', 'Bárbara Costa de Sá Barreto', 'Terapia Ocupacional'),
  ('Realengo', '5', 4, 'Manhã', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '5', 4, 'Manhã', 'Liliane de Oliveira Lima', 'Terapia Ocupacional'),
  ('Realengo', '5', 4, 'Tarde', 'Bárbara Costa de Sá Barreto', 'Terapia Ocupacional'),
  ('Realengo', '5', 4, 'Tarde', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '5', 4, 'Tarde', 'Liliane de Oliveira Lima', 'Terapia Ocupacional'),
  ('Realengo', '5', 5, 'Manhã', 'Elisangela Motta Do Valle', 'Terapia Ocupacional'),
  ('Realengo', '5', 5, 'Manhã', 'Julliana de Oliveira Mota', 'Terapia Ocupacional'),
  ('Realengo', '5', 5, 'Manhã', 'Maria Alice Sarmento Jarcem', 'Terapia Ocupacional'),
  ('Realengo', '5', 5, 'Tarde', 'Danielle Galvão Nogueira', 'Terapia Ocupacional'),
  ('Realengo', '5', 5, 'Tarde', 'Elisangela Motta Do Valle', 'Terapia Ocupacional'),
  ('Realengo', '5', 5, 'Tarde', 'Julliana de Oliveira Mota', 'Terapia Ocupacional'),
  ('Realengo', '6', 1, 'Manhã', 'Ingrid Cristina Mello da Costa Dutra', 'Psicopedagogia'),
  ('Realengo', '6', 1, 'Tarde', 'Ingrid Cristina Mello da Costa Dutra', 'Psicopedagogia'),
  ('Realengo', '6', 2, 'Tarde', 'Ingrid Cristina Mello da Costa Dutra', 'Psicopedagogia'),
  ('Realengo', '6', 3, 'Manhã', 'Ingrid Cristina Mello da Costa Dutra', 'Psicopedagogia'),
  ('Realengo', '6', 3, 'Tarde', 'Ingrid Cristina Mello da Costa Dutra', 'Psicopedagogia'),
  ('Realengo', '6', 4, 'Manhã', 'Ingrid Cristina Mello da Costa Dutra', 'Psicopedagogia'),
  ('Realengo', '6', 4, 'Tarde', 'Ingrid Cristina Mello da Costa Dutra', 'Psicopedagogia'),
  ('Realengo', '6', 5, 'Tarde', 'Leonardo Nascimento Bassi', 'Psicopedagogia'),
  ('Realengo', '7', 1, 'Tarde', 'Paula Quintanilha De Sousa', 'Psicopedagogia'),
  ('Realengo', '7', 2, 'Manhã', 'Paula Quintanilha De Sousa', 'Psicopedagogia'),
  ('Realengo', '7', 2, 'Manhã', 'Yasmin Souza Meirelles Oliveira', 'Psicopedagogia'),
  ('Realengo', '7', 2, 'Tarde', 'Paula Quintanilha De Sousa', 'Psicopedagogia'),
  ('Realengo', '7', 3, 'Manhã', 'Rodrigo Magalhães do Nascimento', 'Fonoaudiologia'),
  ('Realengo', '7', 3, 'Manhã', 'Yasmin Souza Meirelles Oliveira', 'Psicopedagogia'),
  ('Realengo', '7', 3, 'Tarde', 'Rodrigo Magalhães do Nascimento', 'Fonoaudiologia'),
  ('Realengo', '7', 4, 'Tarde', 'Sabrina Santos Theobaldo', 'Psicopedagogia'),
  ('Realengo', '7', 5, 'Manhã', 'Maria Eduarda Marrocos', 'Fonoaudiologia'),
  ('Realengo', '7', 5, 'Tarde', 'Amanda Martins Rodrigues', 'Psicopedagogia'),
  ('Realengo', '7', 5, 'Tarde', 'Sabrina Santos Theobaldo', 'Psicopedagogia'),
  ('Realengo', '8', 1, 'Manhã', 'Juliana Fraga Sampaio', 'Terapia Alimentar'),
  ('Realengo', '8', 1, 'Manhã', 'Mariana Defante', 'Terapia Alimentar'),
  ('Realengo', '8', 1, 'Tarde', 'Juliana Fraga Sampaio', 'Terapia Alimentar'),
  ('Realengo', '8', 1, 'Tarde', 'Mariana Defante', 'Terapia Alimentar'),
  ('Realengo', '8', 2, 'Manhã', 'Juliana Fraga Sampaio', 'Terapia Alimentar'),
  ('Realengo', '8', 2, 'Manhã', 'Mariana Defante', 'Terapia Alimentar'),
  ('Realengo', '8', 2, 'Tarde', 'Juliana Fraga Sampaio', 'Terapia Alimentar'),
  ('Realengo', '8', 2, 'Tarde', 'Mariana Defante', 'Terapia Alimentar'),
  ('Realengo', '8', 3, 'Manhã', 'Camila Ferreira Rios Gomes', 'Terapia Alimentar'),
  ('Realengo', '8', 3, 'Manhã', 'Juliana Fraga Sampaio', 'Terapia Alimentar'),
  ('Realengo', '8', 3, 'Tarde', 'Camila Ferreira Rios Gomes', 'Terapia Alimentar'),
  ('Realengo', '8', 3, 'Tarde', 'Juliana Fraga Sampaio', 'Terapia Alimentar'),
  ('Realengo', '8', 4, 'Manhã', 'Camila Ferreira Rios Gomes', 'Terapia Alimentar'),
  ('Realengo', '8', 4, 'Tarde', 'Camila Ferreira Rios Gomes', 'Terapia Alimentar'),
  ('Realengo', '8', 5, 'Tarde', 'Camila Ferreira Rios Gomes', 'Terapia Alimentar')
) as v(unidade_nome, numero_sala, dow, turno, profissional_nome, terapia_nome)
join public.cronograma_salas s
  on s.unidade_nome = v.unidade_nome
 and s.numero_sala  = v.numero_sala;
